In [ ]:
# https://github.com/parulnith/Building-a-Simple-Chatbot-in-Python-using-NLTK/blob/master/chatbot.py
# https://codequs.com/p/B1dv133FN


In [ ]:
#Meet Robo: your friend

#import necessary libraries
import io
import random
import string # to process standard python strings
import warnings
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('popular', quiet=True) # for downloading packages

# uncomment the following only the first time
#nltk.download('punkt') # first-time use only
#nltk.download('wordnet') # first-time use only

from google.colab import drive
drive.mount('/content/drive')

#Reading in the corpus
with open('/content/drive/MyDrive/Chromebook DESK/NU MSDS/453 Natural Language/chatbot6.txt','r', encoding='utf8', errors ='ignore') as fin:
    raw = fin.read().lower()

#TOkenisation
sent_tokens = nltk.sent_tokenize(raw)# converts to list of sentences 
word_tokens = nltk.word_tokenize(raw)# converts to list of words

# Preprocessing
lemmer = WordNetLemmatizer()
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))


# Keyword Matching
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["hi", "hey", "*nods*", "hi there", "hello", "I am glad! You are talking to me"]

def greeting(sentence):
    """If user's input is a greeting, return a greeting response"""
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)


# Generating response
def response(user_response):
    robo_response=''
    sent_tokens.append(user_response)
    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx=vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf==0):
        robo_response=robo_response+"I am sorry! I don't understand you"
        return robo_response
    else:
        robo_response = robo_response+sent_tokens[idx]
        return robo_response

flag=True
print("ROBO: My name is Robo. I will answer your queries about Chatbots. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("ROBO: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("ROBO: "+greeting(user_response))
            else:
                print("ROBO: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("ROBO: Bye! take care..")    

Mounted at /content/drive
ROBO: My name is Robo. I will answer your queries about Chatbots. If you want to exit, type Bye!
hi
ROBO: I am glad! You are talking to me
What is the thirteenth amendment?
ROBO: the thirteenth amendment abolished slavery.
What was the Dred Scott decision?
ROBO: dred scott v. sanford was the supreme court decision that said slaves were property and not citizens and that congress had no right to ban slavery in the territories.
Who was King George?
ROBO: "king george iii was the king of england who disbanded the colonial legislatures, taxed the colonies, and refused the olive branch petition leading to the final break with the colonies."
Who was Sam Adams?
ROBO: sam adams was a member of the sons of liberty who started the committee of correspondence to stir public support for american independence.
Who wrote the Declaration of Independence?
ROBO: "independence hall in philadelphia, pennsylvania is the site where the declaration of independence and the constitut

In [ ]:
my_doc1 =  "What is the thirteenth amendment"

my_doc2 =  "What was the Dred Scott decision?"

my_doc3 =  "Who was King George?"

my_doc4 =  "Who was Sam Adams?"

my_doc5 =  "Who wrote the Declaration of Independence?"

documents = [my_doc1, my_doc2, my_doc3, my_doc4, my_doc5]


In [ ]:
# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=[my_doc1, my_doc2, my_doc3, my_doc4, my_doc5])

In [ ]:
df

adams  amendment  ...  who  wrote
What is the thirteenth amendment                0          1  ...    0      0
What was the Dred Scott decision?               0          0  ...    0      0
Who was King George?                            0          0  ...    1      0
Who was Sam Adams?                              1          0  ...    1      0
Who wrote the Declaration of Independence?      0          0  ...    1      1

[5 rows x 18 columns]

In [ ]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))


[[1.         0.36514837 0.         0.         0.18257419]
 [0.36514837 1.         0.20412415 0.20412415 0.16666667]
 [0.         0.20412415 1.         0.5        0.20412415]
 [0.         0.20412415 0.5        1.         0.20412415]
 [0.18257419 0.16666667 0.20412415 0.20412415 1.        ]]


In [ ]:
my_doc1 =  "What is the thirteenth amendment"

my_doc2 =  "What was the Dred Scott decision?"

my_doc3 =  "Who was King George?"

my_doc4 =  "Who was Sam Adams?"

my_doc5 =  "Who wrote the Declaration of Independence?"

my_doc6 =  "Who were the Fathers of Confederation?"

my_doc7 =  "Who was Sir John A. Macdonald?"


documents = [my_doc1, my_doc2, my_doc3, my_doc4, my_doc5, my_doc6, my_doc7]

In [ ]:
import gensim
# upgrade gensim if you can't import softcossim
from gensim.matutils import softcossim 
from gensim import corpora
import gensim.downloader as api
from gensim.utils import simple_preprocess
print(gensim.__version__)

3.6.0


In [ ]:
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')


[==================================================] 100.0% 958.5/958.4MB downloaded


In [ ]:
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

# Prepare the similarity matrix
similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

# Convert the sentences into bag-of-words vectors.
sent_1 = dictionary.doc2bow(simple_preprocess(my_doc1))
sent_2 = dictionary.doc2bow(simple_preprocess(my_doc2))
sent_3 = dictionary.doc2bow(simple_preprocess(my_doc3))
sent_4 = dictionary.doc2bow(simple_preprocess(my_doc4))
sent_5 = dictionary.doc2bow(simple_preprocess(my_doc5))
sent_6 = dictionary.doc2bow(simple_preprocess(my_doc6))
sent_7 = dictionary.doc2bow(simple_preprocess(my_doc7))

sentences = [sent_1, sent_2, sent_3, sent_4, sent_5, sent_6, sent_7]

In [ ]:
# Compute soft cosine similarity
print(softcossim(sent_1, sent_7, similarity_matrix))

0.3295979395057943


In [ ]:
import numpy as np
import pandas as pd

def soft_cosine_similarity_matrix(sentences):
    len_array = np.arange(len(sentences))
    xx, yy = np.meshgrid(len_array, len_array)
    cossim_mat = pd.DataFrame([[round(softcossim(sentences[i],sentences[j], similarity_matrix) ,2) for i, j in zip(x,y)] for y, x in zip(xx, yy)])
    return cossim_mat

soft_cosine_similarity_matrix(sentences)

0     1     2     3     4     5     6
0  1.00  0.73  0.39  0.34  0.59  0.55  0.33
1  0.73  1.00  0.57  0.54  0.63  0.60  0.51
2  0.39  0.57  1.00  0.72  0.47  0.52  0.74
3  0.34  0.54  0.72  1.00  0.40  0.46  0.70
4  0.59  0.63  0.47  0.40  1.00  0.72  0.37
5  0.55  0.60  0.52  0.46  0.72  1.00  0.43
6  0.33  0.51  0.74  0.70  0.37  0.43  1.00